# Generated by Django 4.2.1 on 2023-06-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blocked_users',
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked', to='blog.userprofile')),
                ('user_blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocker', to='blog.userprofile')),
            ],
        ),
    ]
