# Generated by Django 4.2.1 on 2023-06-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_blocked_users_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='user_blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='blog.userprofile'),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='user_blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_users', to='blog.userprofile'),
        ),
    ]
